options(stringsAsFactors = FALSE)
## 1. Merges the training and the test sets to create one data set.
## Read in and merge the train and test datasets of all features.
mergedata <- function(trainfile = "UCI HAR Dataset/train/X_train.txt", 
                      trainactivity = "UCI HAR Dataset/train/y_train.txt",
                      trainsub = "UCI HAR Dataset/train/subject_train.txt",
                      testfile = "UCI HAR Dataset/test/X_test.txt",
                      testactivity = "UCI HAR Dataset/test/y_test.txt",
                      testsub = "UCI HAR Dataset/test/subject_test.txt"){
  train <- cbind(read.table(trainsub), read.table(trainactivity), read.table(trainfile))
  test <- cbind(read.table(testsub), read.table(testactivity), read.table(testfile))
  rbind(train, test)
}
## 2. Extracts only the measurements on the mean and standard deviation for each measurement.
## Function `meanstdlabel` gets a dataframe of variable labels and names of features 
## with means and standard deviations.
meanstdlabel <- function(f = "UCI HAR Dataset/features.txt"){
  total <- read.table(f)
  total[grepl("mean", total[,2]) | grepl("std", total[,2]),]
}
## Function `extractdata` extracts the means and standard deviations by the filter.
## Parameter "dataset" and "filter" should be generated by functions 
## `mergedata` and `meanstdlabel` respectively.
extractdata <- function(dataset, filter){
  filtered <- dataset[,c(1,2,filter[,1] + 2)]
  filtered
}
## 3. Uses descriptive activity names to name the activities in the dataset.
nameactivity <- function(dataset, 
                         activitynames = "UCI HAR Dataset/activity_labels.txt") {
  anames <- read.table(activitynames)
  dataset[,2] <- sapply(dataset[,2], function(x) anames[anames[,1]==x,2])
  dataset
}
## 4. Appropriately labels the data set with descriptive variable names.
## Parameter "dataset" and "filter" should be generated by functions 
## `nameactivity` and `meanstdlabel` respectively.
namevar <- function(dataset, filter) {
  colnames(dataset) <- c("subject","activity",filter[,2])
  dataset
}
## 5. From the data set in step 4, creates a second, independent tidy data set 
## with the average of each variable for each activity and each subject.
avevar <- function(dataset) {
  allsub <- sort(unique(dataset[,1]))
  allact <- sort(unique(dataset[,2]))
  newset <- list()
  k <- 1
  for (i in allsub) {
    for (j in allact) {
      temp <- sapply(dataset[(dataset[,1] == i) & (dataset[,2] == j),-(1:2)],mean)
      newset[[k]] <- c(i,j,temp)
      k <- k + 1
    }
  }
  newset <- as.data.frame(t(as.data.frame(newset)))
  newset[,1] <- as.integer(newset[,1])
  for (i in 3:ncol(newset)) {
    newset[,i] <- as.numeric(newset[,i])
  }
  colnames(newset) <- colnames(dataset)
  row.names(newset) <- paste("average",1:nrow(newset))
  newset
}
## Body to get and clean the data.
filter1 <- meanstdlabel()
data1 <- mergedata()
data2 <- extractdata(data1, filter1)
data3 <- nameactivity(data2)
data4 <- namevar(data3, filter1)
data5 <- avevar(data4)
write.table(data5, "tidy data set.txt", row.names = FALSE)